transmission:
  build: ../transmission
  dockerfile: Dockerfile
  restart: always
  container_name: transmission
  ports:
    - 9091:9091
  environment:
    - TZ=Australia/Melbourne
    - TR_IDLE_SEEDING_LIMIT_ENABLED=true
    - TR_IDLE_SEEDING_LIMIT=1
    - TR_RATIO_LIMIT_ENABLED=true
    - TR_RATIO_LIMIT=1
    - TR_DOWNLOAD_DIR=/downloads
    - TR_INCOMPLETE_DIR_ENABLED=false
    - TR_RENAME_PARTIAL_FILES=true
    - TR_DHT_ENABLED=false
    - TR_PEX_ENABLED=false
    - USERID=1000
    - GROUPID=1000
  volumes:
    - ~/transmission:/var/lib/transmission-daemon/info
    #set transmission or sonarr download folder to /downloads
    - /media/nas/series:/downloads
    - ~/tmp:/var/lib/transmission-daemon/incomplete
deluge:
  image: linuxserver/deluge
  restart: always
  container_name: deluge
  ports:
    - 8112:8112
  environment:
    - TZ=Australia/Melbourne
    - PGID=1001
    - PUID=1001
  volumes:
    - ~/deluge/config:/var/lib/transmission-daemon/info
    #set transmission or sonarr download folder to /downloads
    - /media/nas/movies:/downloads
jackett:
  build: ../docker-jackett/
  dockerfile: Dockerfile
  restart: always
  container_name: jackett
  ports:
    - 9117:9117
  links:
    - transmission
  environment:
    - TZ=Australia/Melbourne
    - PUID=1000
    - PGID=1000
  volumes:
    - ~/jackett/config:/config
    - ~/media:/downloads
sonarr:
  build: ../docker-sonarr/
  dockerfile: Dockerfile
  restart: always
  container_name: sonarr
  links:
    - transmission
    - jackett
  environment:
    - TZ=Australia/Melbourne
    - PUID=1000
    - PGID=1000
  ports:
    - 8989:8989
    - 9898:9898
  volumes:
    - /media/nas/series:/volumes/completed
    - /media/nas/series:/volumes/media
    - ~/sonarr/config:/volumes/config
radarr:
  build: ../docker-radarr/
  dockerfile: Dockerfile
  restart: always
  container_name: radarr
  links:
    - deluge
    - jackett
  environment:
    - TZ=Australia/Melbourne
    - PUID=1000
    - PGID=1000
  ports:
    - 7878:7878
  volumes:
    - ~/radarr/config:/config
    - /media/nas/movies:/downloads
    - /media/nas/movies:/movies
