plex:
  build: ../pms-docker
  dockerfile: Dockerfile
  restart: unless-stopped
  container_name: plex
  ports:
    - 32400:32400
    - 3005:3005
    - 8324:8324
    - 32469:32469
    - 1900:1900
    - 32410:32410
    - 32412:32412
    - 32413:32413
    - 32414:32414
  environment:
    - TZ=Australia/Melbourne
  volumes:
    - /Users/conare/plex/database:/config
    - /Users/conare/plex/transcode:/transcode
    - /Users/conare/media:/data

transmission:
  build: ../transmission
  dockerfile: Dockerfile
  restart: unless-stopped
  container_name: transmission
  links:
    - plex
  ports:
    - 9091:9091
  environment:
    - TZ=Australia/Melbourne
    - TR_IDLE_SEEDING_LIMIT_ENABLED=true
    - TR_IDLE_SEEDING_LIMIT=1
    - TR_RATIO_LIMIT_ENABLED=true
    - TR_RATIO_LIMIT=4
    - TR_DOWNLOAD_DIR=/downloads
    - TR_INCOMPLETE_DIR_ENABLED=false
    - TR_RENAME_PARTIAL_FILES=true
    - TR_DHT_ENABLED=false
    - TR_PEX_ENABLED=false
    - USERID=1000
    - GROUPID=1000
  volumes:
    - /Users/conare/transmission:/var/lib/transmission-daemon/info
    #set transmission or sonarr download folder to /downloads
    - /Users/conare/media:/downloads
    - /Users/conare/tmp:/var/lib/transmission-daemon/incomplete

jackett:
  build: ../docker-jackett/
  dockerfile: Dockerfile
  container_name: jackett
  ports:
    - 9117:9117
  links:
    - transmission
    - plex
  environment:
    - TZ=Australia/Melbourne
    - PUID=1000
    - PGID=1000
  volumes:
    - /Users/conare/completed:/config 
    - /Users/conare/media:/downloads

sonarr:
  build: ../docker-sonarr/
  dockerfile: Dockerfile
  restart: unless-stopped
  container_name: sonarr
  links:
    - transmission
    - plex
    - jackett
  environment:
  - TZ=Australia/Melbourne
  - PUID=1000
  - PGID=1000
  ports:
    - 8989:8989
    - 9898:9898
  volumes:
    - /Users/conare/completed:/volumes/completed
    - /Users/conare/media:/volumes/media